apiVersion: v1
kind: ConfigMap
metadata:
  name: tars-upload-proxy-caddy
  namespace: tars-common
  labels:
    app: tars-upload-proxy
data:
  Caddyfile: |
    :9000
    reverse_proxy {
      to 10.11.241.51:9000
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tars-upload-proxy
  namespace: tars-common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tars-upload-proxy
  template:
    metadata:
      labels:
        app: tars-upload-proxy
    spec:
      containers:
      - name: caddy
        image: image-registry.openshift-image-registry.svc:5000/tars-images/caddy:alpine
        imagePullPolicy: Always
        command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/caddy/Caddyfile
          name: tars-upload-proxy-caddy
          subPath: Caddyfile
      volumes:
      - name: tars-upload-proxy-caddy
        configMap:
          defaultMode: 420
          name: tars-upload-proxy-caddy
          items:
          - key: Caddyfile
            path: Caddyfile
---
apiVersion: v1
kind: Service
metadata:
  name: tars-upload-proxy
  namespace: tars-common
  labels:
    app: tars-upload-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app: tars-upload-proxy
---
apiVersion: v1
kind: Route
metadata:
  name: tars-upload-proxy
  annotations:
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: tars-upload-proxy
